# Stage 1: Load the project
FROM ghcr.io/ba-st/pharo-loader:v10.0.0 as loader

COPY --chown=pharo:users ./source/ ./source/
COPY --chown=pharo:users ./.git/ ./.git/
RUN pharo metacello install gitlocal://./source BaselineOfCurrencyAPI --groups=Worker-Deployment

# Stage 2: Copy the resulting Pharo.image with our project loaded
# into a new launchpad-based docker image
FROM ghcr.io/ba-st/launchpad:v4

COPY --from=loader /opt/pharo/Pharo.image ./
COPY --from=loader /opt/pharo/Pharo.changes ./
COPY --from=loader /opt/pharo/Pharo*.sources ./

RUN mkdir logs \
  && mkdir data \
  && chown --recursive pharo:users /opt/pharo

USER pharo

CMD [ "launchpad-start" , "currency-exporter" ]
