name: 'GS64 test'

on: [push,workflow_dispatch]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: GS64 testing
    steps:
      - uses: actions/checkout@v3
      - name: Test
        id: gstest
        uses: ba-st-actions/gs64-ci@release-candidate
        with:
          project_name: 'Currency-API'
