name: Baseline Groups

on: [push,pull_request,workflow_dispatch]

jobs:
   group-loading:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-10 ]
        load-spec: [ api-deployment, worker-deployment, tests, development ]
    name: ${{ matrix.smalltalk }} + ${{ matrix.load-spec }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Set up PostgreSQL
        run: |
          docker run -d -p 127.0.0.1:5432:5432 \
            -e POSTGRES_PASSWORD=secret \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_DB=test \
            postgres:14 \
            -c ssl=on \
            -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem \
            -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
      - name: Set up RabbitMQ
        run: |
          docker run -d -p 127.0.0.1:5672:5672 \
            rabbitmq:latest
      - name: Load group in image
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalkci/loading.${{ matrix.load-spec }}.ston
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
