name: Unit Tests

on: [push,pull_request,workflow_dispatch]

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ Pharo64-10 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Smalltalk CI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Set up PostgreSQL
        run: |
          docker run -d -p 127.0.0.1:5432:5432 \
            -e POSTGRES_PASSWORD=secret \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_DB=test \
            postgres:14 \
            -c ssl=on \
            -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem \
            -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
      - name: Set up RabbitMQ
        run: |
          docker run -d -p 127.0.0.1:5672:5672 \
            rabbitmq:latest
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalkci/unit-tests.ston
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: Unit-Tests-${{matrix.smalltalk}}
